/*
    ROUTING MODEL for MAL
*/

const express = require('express');
const router = express.Router();
// const passport = require('passport');
const moment = require('moment');
const db = require("../models");

const multer = require('multer');
const upload = multer();
const open = require('open');






// User model
const User = db.users;
const MAL = db.mal;
const Update = db.updates;
const SupplementalAssociationInfo = db.supplementalAssociationInfo;
const GeneralBoardInfo = db.generalBoardInfo;
const RepresentationInquiries = db.representationInquiries;
const MerchandiseMug = db.merchandiseMug;
const MerchandiseFloridaStatue = db.merchandiseFloridaStatue;
const SocialMedia = db.socialMedia;
const HiringRecord = db.hiringRecord;
const TerminationRecord = db.terminationRecord;
const ReferralSource = db.referralSource;
const ReferralMgmtCoVendor = db.referralMgmtCoVendor;
const Presentations = db.presentations;
const PotentialClientReports = db.potentialClientReports;

// Ensure authenticated user is logged in
const {
    ensureAuthenticated
} = require('../config/auth');

// ------------------------------------------------------------------

// GET home page
router.get('/dashboard', ensureAuthenticated, async function (req, res, next) {
    req.flash('success', "Please choose an action from the top menu");
    res.locals.message = req.flash();
    req.app.locals.user = req.user;
    res.render('pages/mal/dashboard', );
});

// GET create page
router.get('/create', ensureAuthenticated, async function (req, res, next) {
    req.app.locals.user = req.user;
    req.app.locals.date = moment().format('MMMM Do YYYY');
    res.render('pages/mal/create', );
});

// Create handle
/*
    - Couple of notes below:
    - I know this code is a mess but I've tried my best to document it the best way possible and record which chunks post to which table
    - Please know this code is intentional and should flow logically based on how elements appear on the associated view
    - All create statements execute inside of the original mal.model.js create .then block
    - To prevent HTML element naming collisions, element names will usually contain a 'header' such as general,supplemental, social, etc.
        - This is intentional, and while ugly, does the job
    - To prevent database datatype storage errors, ALL element values are parsed
        - If an element's value is '', it is replaced with null
        - IMPORTANT: Dates are parsed based on if 'date' (case-insensitive) is in the name
            - If substring 'date' is found within key, the value is either left as null OR converted to appropriate database DATEONLY value through 'databaseDate' function found at the bottom of this file
            - This means only variables that store DATEONLY values should use 'date' in their respective names
    - Transactions: Either all records are successfully created or none of them are; Maybe a try block
*/
// TODO: [Transactions] Force atomicity on this entire route.
router.post('/create', ensureAuthenticated, function (req, res, next) {
    var malID;
    // Retrieve associated element valuesfrom page & structure them
    const {
        // --Primary Association Information--
        LegalName,
        Aka,
        ClientAcctNum,
        FileName,
        StatusInFirm,
        SpecialClassification,
        AsscType,
        ScndMHPAssc,
        DomicileCounty,
        DomicileCity,
        DomicileZip,
        // --Association Photo--
        AssociationPhoto
    } = req.body;
    // Create mal object
    var newEntry = {
        // --Metadata--
        // creation: AUTOGENERATED,
        originator: req.user.fName + " " + req.user.lName,
        // --Primary Association Information--
        legalName: LegalName,
        aka: Aka,
        clientAcctNum: ClientAcctNum,
        fileName: FileName,
        statusInFirm: StatusInFirm,
        specialClassification: SpecialClassification,
        asscType: AsscType,
        scndMHPAssc: ScndMHPAssc,
        domicileCounty: DomicileCounty,
        domicileCity: DomicileCity,
        domicileZip: DomicileZip,
        // --Association Photo--
        associationPhoto: AssociationPhoto,
    };
    // Replace all empty string values with NULL
    for (let key of Object.keys(newEntry)){
        if (newEntry[key] == '') {
            newEntry[key] = null;
        }
    }
    // Create MAL entry with object data
    MAL.create(newEntry)
                .then(data => {
                    // record entry ID
                    malID = data.id;

                    // updates.model.js -------------------------------------------------------------------------------------------------
                    const {
                        UpdateNote
                    } = req.body;
                    // update tracking JSON
                    updateTrackingJSON = {
                        "type":"CREATE",
                        "log": [
                            { "field":"", "before":"", "after":"" },
                        ]
                    }
                    // Record attributes
                    var entryUpdate = {
                        MALrelatedID: malID,
                        relatedTable: 'MAL',
                        updateAuthor: data.originator,
                        updateTracking: JSON.stringify(updateTrackingJSON),
                        updateNote: UpdateNote
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryUpdate)){
                        if (entryUpdate[key] == '') {
                            entryUpdate[key] = null;
                        }
                    }
                    // Create new update record
                    Update.create(entryUpdate)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *UPDATE* record not added.');
                        });



                    // mal_SupplementalAssociationInfo.model.js -----------------------------------------------------------------------------

                    const {
                        // View element values
                        SupplementalDesignatedSiteAddress,
                        SupplementalCity,
                        SupplementalZipCode,
                        SupplementalPhoneNumber,
                        SupplementalAssociationWebsite,
                        SupplementalAssociationEmail,
                        SupplementalNumberUnitsLotsDeveloped,
                        SupplementalCommunity55Plus,
                        SupplementalAssociationControlledBy,
                        SupplementalApproxTurnoverDate,
                        SupplementalMasterOrSub,
                        SupplementalSubAssociations,
                        SupplementalMasterAssociation,
                        SupplementalRegisteredAgent,
                        SupplementalDateRA,
                        SupplementalClubhouse,
                        SupplementalAssessments,
                        SupplementalWhatIntervals,
                        SupplementalAvailableToRent,
                        SupplementalPrice,
                        SupplementalTheaterSeatingAmount,
                        SupplementalTableChairsAmount,
                        SupplementalTypeOfTables,
                        SupplementalAdditionalNotes,
                    } = req.body;
                    // Record attributes
                    var entrySupplemental = {
                        MALrelatedID: malID,
                        designatedSiteAddress: SupplementalDesignatedSiteAddress,
                        city: SupplementalCity,
                        zipCode: SupplementalZipCode,
                        phoneNumber: SupplementalPhoneNumber,
                        associationWebsite: SupplementalAssociationWebsite,
                        associationEmail: SupplementalAssociationEmail,
                        numberUnitsLotsDeveloped: SupplementalNumberUnitsLotsDeveloped,
                        community55Plus: SupplementalCommunity55Plus,
                        associationControlledBy: SupplementalAssociationControlledBy,
                        approxTurnoverDate: SupplementalApproxTurnoverDate,
                        masterOrSub: SupplementalMasterOrSub,
                        subAssociations: SupplementalSubAssociations,
                        masterAssociation: SupplementalMasterAssociation,
                        registeredAgent: SupplementalRegisteredAgent,
                        dateRA: SupplementalDateRA,
                        clubhouse: SupplementalClubhouse,
                        assessments: SupplementalAssessments,
                        whatIntervals: SupplementalWhatIntervals,
                        availableToRent: SupplementalAvailableToRent,
                        price: SupplementalPrice,
                        theaterSeatingAmount: SupplementalTheaterSeatingAmount,
                        tableChairsAmount: SupplementalTableChairsAmount,
                        typeOfTables: SupplementalTypeOfTables,
                        additionalNotes: SupplementalAdditionalNotes
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entrySupplemental)){
                        if (entrySupplemental[key] == '') {
                            entrySupplemental[key] = null;
                        }
                    }
                    // Create new SupplementalAssociationInfo record
                    SupplementalAssociationInfo.create(entrySupplemental)
                        .then(data1 => {
                            // Update MAL entry with corresponding SupplementalAssociationInfo table ID
                            MAL.update(
                                {supplementalAssociationInfoID: data1.id},
                                {where: {id:malID}}
                            )
                            .catch(err => {
                                console.log(err);
                                req.flash('failure','Failed to update MAL entry\'s "supplementalAssociationInfoID"');
                            });
                        })
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_SupplementalAssociationInfo* record not added.');
                        });



                    // mal_GeneralBoardInfo.model.js --------------------------------------------------------------------------------------
                    const {
                        GeneralCorporateStatus,
                        GeneralAnnualMeetingMonth,
                        GeneralLastCorporateReportDate,
                        GeneralCurrentBoardExpirationDate,
                        GeneralAssociationSeminarAdmittandance,
                        GeneralAssociationSeminarTagColor,
                        GeneralNumberDirectorsFullyStaffed,
                        GeneralDateAssociationUpdatedWhole,
                    } = req.body;
                    //
                    var entryGeneralBoard = {
                        MALrelatedID: malID,
                        corporateStatus: GeneralCorporateStatus,
                        annualMeetingMonth: GeneralAnnualMeetingMonth,
                        lastCorporateReportDate: GeneralLastCorporateReportDate,
                        currentBoardExpirationDate: GeneralCurrentBoardExpirationDate,
                        associationSeminarAdmittandance: GeneralAssociationSeminarAdmittandance,
                        associationSeminarTagColor: GeneralAssociationSeminarTagColor,
                        numberDirectorsFullyStaffed: GeneralNumberDirectorsFullyStaffed,
                        dateAssociationUpdatedWhole: GeneralDateAssociationUpdatedWhole,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryGeneralBoard)){
                        if (entryGeneralBoard[key] == '') {
                            entryGeneralBoard[key] = null;
                        }
                    }
                    // Create new update record
                    GeneralBoardInfo.create(entryGeneralBoard)
                        .then(data1 => {
                            // Update MAL entry with corresponding update table ID
                            MAL.update(
                                {generalBoardTableID: data1.id},
                                {where: {id:malID}}
                            )
                            .catch(err => {
                                console.log(err);
                                req.flash('failure','Failed to update MAL entry\'s "supplementalAssociationInfoID"');
                            });
                        })
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_SupplementalAssociationInfo* record not added.');
                        });



                    // mal_RepresentationInquiries.model.js -------------------------------------------------------------------------------
                    const {
                        RepresentCmServicesRequest,
                        RepresentOriginationSource,
                        RepresentCmSponsored,
                        RepresentSource,
                        RepresentDateRequested,

                    } = req.body;
                    //
                    var entryRepresentationInq = {
                        MALrelatedID: malID,
                        cmServicesRequest: RepresentCmServicesRequest,
                        originationSource: RepresentOriginationSource,
                        cmSponsored: RepresentCmSponsored,
                        source: RepresentSource,
                        dateRequested: RepresentDateRequested
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryRepresentationInq)){
                        if (entryRepresentationInq[key] == '') {
                            entryRepresentationInq[key] = null;
                        }
                    }
                    // Create new update record
                    RepresentationInquiries.create(entryRepresentationInq)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_RepresentationInquiries* record not added.');
                        });
                    
                    

                    // mal_MerchandiseMug.model.js ----------------------------------------------------------------------------------------
                    const {
                        MugPurchaseStatus,
                        MugOriginationSaleSource,
                        MugDatePurchased,
                        MugQuantity,
                        MugDeliveryMethod,
                        MugPaymentMethod,
                        MugCheckNumber,
                    } = req.body;
                    //
                    var entryMugPurchase = {
                        MALrelatedID: malID,
                        mugPurchaseStatus: MugPurchaseStatus,
                        originationSaleSource: MugOriginationSaleSource,
                        datePurchased: MugDatePurchased,
                        quantity: MugQuantity,
                        deliveryMethod: MugDeliveryMethod,
                        paymentMethod: MugPaymentMethod,
                        checkNumber: MugCheckNumber,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryMugPurchase)){
                        if (entryMugPurchase[key] == '') {
                            entryMugPurchase[key] = null;
                        }
                    }
                    // Create new update record
                    MerchandiseMug.create(entryMugPurchase)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_MerchandiseMug* record not added.');
                        });
                    
                    

                    // mal_MerchandiseFloridaStatue.model.js ------------------------------------------------------------------------------
                    const {
                        StatueStatusPurchase,
                        StatueRequestedDate,
                        StatueQuantity,
                        StatueWhichBook,
                        StatueReferralSource,
                        StatueReferralSourceOther,
                        StatueSoldBy,
                        StatueDeliveryMethod,
                        StatuePaymentMethod,
                        StatueCheckNumber,
                    } = req.body;
                    //
                    var entryFloridaStatue = {
                        MALrelatedID: malID,
                        statuePurchaseStatus:StatueStatusPurchase,
                        dateRequested:StatueRequestedDate,
                        quantity:StatueQuantity,
                        whichBook:StatueWhichBook,
                        referralSource:StatueReferralSource,
                        referralSourceOther:StatueReferralSourceOther,
                        soldBy:StatueSoldBy,
                        deliveryMethod:StatueDeliveryMethod,
                        paymentMethod:StatuePaymentMethod,
                        checkNumber:StatueCheckNumber,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryFloridaStatue)){
                        if (entryFloridaStatue[key] == '') {
                            entryFloridaStatue[key] = null;
                        }
                    }
                    // Create new update record
                    MerchandiseFloridaStatue.create(entryFloridaStatue)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_SupplementalAssociationInfo* record not added.');
                        });

                    
                    
                    // mal_SocialMedia.model.js -------------------------------------------------------------------------------------------
                    const {
                        SocialNoSocialMedia,
                        SocialHasFacebook,
                        SocialFacebookAccount,
                        SocialFacebookDate,
                        SocialHasLinkedin,
                        SocialLinkedinAccount,
                        SocialLinkedinDate,
                        SocialHasTwitter,
                        SocialTwitterAccount,
                        SocialTwitterDate,
                        SocialHasInstagram,
                        SocialInstagramAccount,
                        SocialInstagramDate,
                    } = req.body;

                    var entrySocial = {
                        MALrelatedID: malID,
                        noSocialMedia:SocialNoSocialMedia,
                        hasFacebook:SocialHasFacebook,
                        facebookAccount:SocialFacebookAccount,
                        facebookDate:SocialFacebookDate,       
                        hasLinkedin:SocialHasLinkedin,
                        linkedinAccount:SocialLinkedinAccount,
                        linkedinDate:SocialLinkedinDate,                 
                        hasTwitter:SocialHasTwitter,
                        twitterAccount:SocialTwitterAccount,
                        twitterDate:SocialTwitterDate,
                        hasInstagram:SocialHasInstagram,
                        instagramAccount:SocialInstagramAccount,
                        instagramDate:SocialInstagramDate,

                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entrySocial)){
                        if (entrySocial[key] == '') {
                            entrySocial[key] = null;
                        }
                    }
                    // Create new update record
                    SocialMedia.create(entrySocial)
                        .then(data1 => {
                            // Update MAL entry with corresponding update table ID
                            MAL.update(
                                {socialMediaID: data1.id},
                                {where: {id:malID}}
                            )
                            .catch(err => {
                                console.log(err);
                                req.flash('failure','Failed to update MAL entry\'s "socialMediaID"');
                            });
                        })
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_SocialMedia* record not added.');
                        });
                    
                    
                    // mal_HiringRecord.model.js ------------------------------------------------------------------------------------------
                    const {
                        HiringDateHired,
                        HiringReasonsHired,
                        HiringComments,
                        HiringTypeofRepresentation,
                        HiringDate,
                        HiringSourceOfReferralName,
                        HiringPosition,
                        HiringCompanyAssociation,
                        HiringPrimaryFirm,
                        HiringOtherFirms,
                        HiringForWhatPurpose,
                        HiringFormerFirm,
                    } = req.body;
                    //
                    var entryHiring = {
                        MALrelatedID: malID,
                        dateHired:HiringDateHired,
                        reasonsHired:HiringReasonsHired,
                        hiringComments:HiringComments,
                        typeofRepresentation:HiringTypeofRepresentation,
                        date:HiringDate,
                        sourceOfReferralName:HiringSourceOfReferralName,
                        position:HiringPosition,
                        companyAssociation:HiringCompanyAssociation,
                        primaryFirm:HiringPrimaryFirm,
                        otherFirms:HiringOtherFirms,
                        forWhatPurpose:HiringForWhatPurpose,
                        formerFirm:HiringFormerFirm,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryHiring)){
                        if (entryHiring[key] == '') {
                            entryHiring[key] = null;
                        }
                    }
                    // Create new update record
                    HiringRecord.create(entryHiring)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_HiringRecord* record not added.');
                        });
                    
                    
                    // mal_TerminationRecord.model.js -------------------------------------------------------------------------------------
                    const {
                        TerminationDateTerminated,
                        TerminationReasonTerminated,
                        TerminationRevenueGenerated,
                        TerminationTerminatingNotes,
                        TerminationOrigin,
                        TerminationRealReasonTerminated,
                    } = req.body;
                    //
                    var entryTermination = {
                        MALrelatedID: malID,
                        dateTerminated:TerminationDateTerminated,
                        reasonTerminated:TerminationReasonTerminated,
                        revenueGenerated:TerminationRevenueGenerated,
                        terminatingNotes:TerminationTerminatingNotes,
                        terminationOrigin:TerminationOrigin,
                        realReasonTerminated:TerminationRealReasonTerminated,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryTermination)){
                        if (entryTermination[key] == '') {
                            entryTermination[key] = null;
                        }
                    }
                    // Create new update record
                    TerminationRecord.create(entryTermination)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_TerminationRecord* record not added.');
                        });
                    
                    
                    // mal_ReferralSource.model.js ----------------------------------------------------------------------------------------
                    const {
                        SourceDate,
                        SourceReferredBy,
                        SourcePosition,
                        SourceCompany,
                        SourceIfOrganizationMeeting,
                    } = req.body;
                    //
                    var entryRefSource = {
                        MALrelatedID: malID,
                        date:SourceDate,
                        referredBy:SourceReferredBy,
                        position:SourcePosition,
                        company:SourceCompany,
                        ifOrganizationMeeting:SourceIfOrganizationMeeting,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryRefSource)){
                        if (entryRefSource[key] == '') {
                            entryRefSource[key] = null;
                        }
                    }
                    // Create new update record
                    ReferralSource.create(entryRefSource)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_ReferralSource* record not added.');
                        });


                    // mal_ReferralMgmtCoVendor.model.js ----------------------------------------------------------------------------------
                    const {
                        MgmtRequestDate,
                        MgmtRequestedBy,
                        MgmtTitle,
                        MgmtForWhatBusiness,
                    } = req.body;
                    // 
                    var entryRefMgmt = {
                        MALrelatedID: malID,
                        requestDate:MgmtRequestDate,
                        requestedBy:MgmtRequestedBy,
                        title:MgmtTitle,
                        forWhatBusiness:MgmtForWhatBusiness,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryRefMgmt)){
                        if (entryRefMgmt[key] == '') {
                            entryRefMgmt[key] = null;
                        }
                    }
                    // Create new update record
                    ReferralMgmtCoVendor.create(entryRefMgmt)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_ReferralMgmtCoVendor* record not added.');
                        });


                    // mal_Presentations.model.js -----------------------------------------------------------------------------------------
                    const {
                        PresentationDate,
                        PresentationRequestedBy,
                        PresentationPosition,
                        PresentationPrimaryAttorney,
                        PresentationStaffMemberAttending,
                        PresentationLocation,
                        PresentationMgmtCoAndOffice,
                        PresentationMethod,
                        PresentationWhoAttendedFromAssociation,
                        PresentationIssuesDiscussed,
                        PresentationTotalPresentationTime,
                        PresentationOutcome,
                        PresentationHired,
                        PresentationReasonsFirmSelected,
                    } = req.body;
                      //  
                    var entryPresentation = {
                        MALrelatedID: malID,
                        date:PresentationDate,
                        requestedBy:PresentationRequestedBy,
                        position:PresentationPosition,
                        primaryAttorney:PresentationPrimaryAttorney,
                        staffMemberAttending:PresentationStaffMemberAttending,
                        location:PresentationLocation,
                        mgmtCoAndOffice:PresentationMgmtCoAndOffice,
                        method:PresentationMethod,
                        whoAttendedFromAssociation:PresentationWhoAttendedFromAssociation,
                        issuesDiscussed:PresentationIssuesDiscussed,
                        totalPresentationTime:PresentationTotalPresentationTime,
                        outcome:PresentationOutcome,
                        hired:PresentationHired,
                        reasonsFirmSelected:PresentationReasonsFirmSelected,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryPresentation)){
                        if (entryPresentation[key] == '') {
                            entryPresentation[key] = null;
                        }
                    }
                    // Create new update record
                    Presentations.create(entryPresentation)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_Presentations* record not added.');
                        });


                    // mal_PotentialClientReports.model.js --------------------------------------------------------------------------------
                    const {
                        PotentialOriginationDatePC,
                        PotentialStaffInitialsPC,
                        PotentialStaffAssignedPC,
                        PotentialNewestEventDate,
                        PotentialStaffInitialsEvent,
                        PotentialFollowUpType,
                        PotentialNextFollowUpDate,
                        PotentialStaffInitialsFollowUp,
                        PotentialFileType,
                        PotentialFileDate,
                        PotentialContactName,
                        PotentialPosition,
                        PotentialPhoneNumber,
                        PotentialExtension,
                        PotentialInfoNote,
                        PotentialCurrentLegalCouncil,
                        PotentialOtherFirmsConsidered,
                        PotentialReasonForLeavingCurrent,
                        PotentialBestAspectCurrent,
                        PotentialDecisionExpected,
                        PotentialDecisionBasis,
                        PotentialSincereRequest3rdParty,
                        PotentialCMNotifiedOnDecision,
                        PotentialCurrentFirmSelection,
                        PotentialAssociationHeardCM,
                        PotentialWhatEvent,
                        PotentialPackageTypeRequested,
                        PotentialCopyToName,
                        PotentialTitle,
                        PotentialMgmtCo,
                        PotentialCopyDate,
                        PotentialEventsChain,
                        PotentialChainDate,
                        PotentialChainOriginator,
                        PotentialChainInitials,
                        PotentialChainInputDate,
                        PotentialEntryTotalTime,
                        PotentialEntryNotes,
                        PotentialFileClosingStatus,
                        PotentialFileClosingDate,
                        PotentialFileRemoveAfter,
                        PotentialClosedFileStatus,
                        PotentialStartingRoundDate,
                        PotentialEndingDate,
                        PotentialClosingDate,
                        PotentialSpentTotalTime,
                        PotentialFirmSelected,
                        PotentialFirmSelectedOtherWhy,
                        PotentialOtherFirmAdditionalReasons,
                        PotentialClosingLetter,
                        PotentialFinalStaffThoughts,
                    } = req.body;
                    //
                    var entryPotential = {
                        MALrelatedID: malID,
                        originationDatePC:PotentialOriginationDatePC,
                        staffInitialsPC:PotentialStaffInitialsPC,
                        staffAssignedPC:PotentialStaffAssignedPC,
                        newestEventDate:PotentialNewestEventDate,
                        staffInitialsEvent:PotentialStaffInitialsEvent,
                        followUpType:PotentialFollowUpType,
                        nextFollowUpDate:PotentialNextFollowUpDate,
                        staffInitialsFollowUp:PotentialStaffInitialsFollowUp,
                        fileType:PotentialFileType,
                        fileDate:PotentialFileDate,
                        contactName:PotentialContactName,
                        position:PotentialPosition,
                        phoneNumber:PotentialPhoneNumber,
                        extension:PotentialExtension,
                        infoNote:PotentialInfoNote,
                        currentLegalCouncil:PotentialCurrentLegalCouncil,
                        otherFirmsConsidered:PotentialOtherFirmsConsidered,
                        reasonForLeavingCurrent:PotentialReasonForLeavingCurrent,
                        bestAspectCurrent:PotentialBestAspectCurrent,
                        decisionExpected:PotentialDecisionExpected,
                        decisionBasis:PotentialDecisionBasis,
                        sincereRequest3rdParty:PotentialSincereRequest3rdParty,
                        CMNotifiedOnDecision:PotentialCMNotifiedOnDecision,
                        currentFirmSelection:PotentialCurrentFirmSelection,
                        associationHeardCM:PotentialAssociationHeardCM,
                        whatEvent:PotentialWhatEvent,
                        packageTypeRequested:PotentialPackageTypeRequested,
                        copyToName:PotentialCopyToName,
                        title:PotentialTitle,
                        mgmtCo:PotentialMgmtCo,
                        copyDate:PotentialCopyDate,
                        eventsChain:PotentialEventsChain,
                        chainDate:PotentialChainDate,
                        chainOriginator:PotentialChainOriginator,
                        chainInitials:PotentialChainInitials,
                        chainInputDate:PotentialChainInputDate,
                        entryTotalTime:PotentialEntryTotalTime,
                        entryNotes:PotentialEntryNotes,
                        fileClosingStatus:PotentialFileClosingStatus,
                        fileClosingDate:PotentialFileClosingDate,
                        fileRemoveAfter:PotentialFileRemoveAfter,
                        closedFileStatus:PotentialClosedFileStatus,
                        startingRoundDate:PotentialStartingRoundDate,
                        endingDate:PotentialEndingDate,
                        closingDate:PotentialClosingDate,
                        spentTotalTime:PotentialSpentTotalTime,
                        firmSelected:PotentialFirmSelected,
                        firmSelectedOtherWhy:PotentialFirmSelectedOtherWhy,
                        otherFirmAdditionalReasons:PotentialOtherFirmAdditionalReasons,
                        closingLetter:PotentialClosingLetter,
                        finalStaffThoughts:PotentialFinalStaffThoughts,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryPotential)){
                        if (entryPotential[key] == '') {
                            entryPotential[key] = null;
                        }
                    }
                    // Create new update record
                    PotentialClientReports.create(entryPotential)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *mal_PotentialClientReports* record not added.');
                        });



                    // Final success code -------------------------------------------------------------------------------------------------
                    req.flash('success','New MAL entry successfully added.');
                    res.locals.message = req.flash();
                    // malID is a variable that stores the ID of a record's ID
                    // What would be the correct syntax to pass the ID along?
                    res.redirect("../mal/entry/" + malID);
                })
                .catch(err => {
                    console.log(err);
                    req.flash('failure','New MAL entry not added.');
                    res.locals.message = req.flash();
                    res.redirect("../mal/create");
                });

});


// TODO: Add table calls for non-Create tables
// GET entry page
router.get('/entry/:id', ensureAuthenticated, async function (req, res, next) {
    req.app.locals.user = req.user;
    req.app.locals.date = moment().format('MMMM Do YYYY');
    const malID = req.params.id;
    // DB call to retrieve record
    req.app.locals.mal = await MAL.findOne(
        {where: {id:malID}},
        { plain: true }
    );
    req.app.locals.update = await Update.findOne(
        {where: {MALrelatedID:malID}},
        {order: ['id','DESC']},
        { plain: true }
    );
    req.app.locals.SupplementalAssociationInfo = await SupplementalAssociationInfo.findOne(
        {where: {MALrelatedID:malID}},
        { plain: true }
    );
    req.app.locals.SupplementalAssociationInfo = await SupplementalAssociationInfo.findOne(
        {where: {MALrelatedID:malID}},
        { plain: true }
    );
    req.app.locals.GeneralBoardInfo = await GeneralBoardInfo.findOne(
        {where: {MALrelatedID:malID}},
        { plain: true }
    );
    req.app.locals.RepresentationInquiries = await RepresentationInquiries.findAll(
        {where: {MALrelatedID:malID}},
        { plain: true }
    );
    req.app.locals.RepresentationInquiries = await RepresentationInquiries.findAll(
        {where: {MALrelatedID:malID}},
        {order: ['id','DESC']},
        { plain: true }
    );
    req.app.locals.MerchandiseMug = await MerchandiseMug.findAll(
        {where: {MALrelatedID:malID}},
        {order: ['id','DESC']},
        { plain: true }
    );
    req.app.locals.MerchandiseFloridaStatue = await MerchandiseFloridaStatue.findAll(
        {where: {MALrelatedID:malID}},
        {order: ['id','DESC']},
        { plain: true }
    );
    req.app.locals.SocialMedia = await SocialMedia.findOne(
        {where: {MALrelatedID:malID}},
        { plain: true }
    );
    req.app.locals.HiringRecord = await HiringRecord.findAll(
        {where: {MALrelatedID:malID}},
        {order: ['id','DESC']},
        { plain: true }
    );
    req.app.locals.HiringRecord = await HiringRecord.findAll(
        {where: {MALrelatedID:malID}},
        {order: ['id','DESC']},
        { plain: true }
    );
    req.app.locals.TerminationRecord = await TerminationRecord.findAll(
        {where: {MALrelatedID:malID}},
        {order: ['id','DESC']},
        { plain: true }
    );
    req.app.locals.ReferralSource = await ReferralSource.findAll(
        {where: {MALrelatedID:malID}},
        {order: ['id','DESC']},
        { plain: true }
    );
    req.app.locals.ReferralMgmtCoVendor = await ReferralMgmtCoVendor.findAll(
        {where: {MALrelatedID:malID}},
        {order: ['id','DESC']},
        { plain: true }
    );
    req.app.locals.Presentations = await Presentations.findAll(
        {where: {MALrelatedID:malID}},
        {order: ['id','DESC']},
        { plain: true }
    );
    req.app.locals.PotentialClientReports = await PotentialClientReports.findAll(
        {where: {MALrelatedID:malID}},
        {order: ['id','DESC']},
        { plain: true }
    );
    res.render('pages/mal/entry', );
});


/*
    INDIVIDUAL TABLE POSTS (UPDATES)
    - The below routes all pertain to updating a specified table's record
*/

// Update MAL Entry's Primary Association Information
router.post('/entry/primary/:id', upload.array(), ensureAuthenticated, async function (req, res, next) {
    // Retrieve associated element values from page & structure them
    const {
        Aka, ClientAcctNum, FileName, StatusInFirm, SpecialClassification, AsscType, ScndMHPAssc, DomicileCounty, DomicileCity, DomicileZip, LegalName, AssociationPhoto
    } = req.body;
    // Update MAL entry with object data
    await MAL.update(
            {legalName: LegalName,
                aka: Aka,
                clientAcctNum: ClientAcctNum,
                fileName: FileName,
                statusInFirm: StatusInFirm,
                specialClassification: SpecialClassification,
                asscType: AsscType,
                scndMHPAssc: ScndMHPAssc,
                domicileCounty: DomicileCounty,
                domicileCity: DomicileCity,
                domicileZip: DomicileZip,
                // --Association Photo--
                associationPhoto: AssociationPhoto
            },
            {where: {id:req.params.id}}
            
        )
        .catch(err => {
            console.log(err);
            req.flash('failure','Failed to update MAL entry\'s mal.model.js');
        });
    
    res.redirect("../../entry/" + req.params.id);
});


// Update MAL Entry's mal_SupplementalAssociationInfo
router.post('/entry/supplemental/:id', ensureAuthenticated, async function (req, res, next) {
    // Retrieve associated element values from page & structure them
    const {
        SupplementalDesignatedSiteAddress,
        SupplementalCity,
        SupplementalZipCode,
        SupplementalPhoneNumber,
        SupplementalAssociationWebsite,
        SupplementalAssociationEmail,
        SupplementalNumberUnitsLotsDeveloped,
        SupplementalCommunity55Plus,
        SupplementalAssociationControlledBy,
        SupplementalApproxTurnoverDate,
        SupplementalMasterOrSub,
        SupplementalSubAssociations,
        SupplementalMasterAssociation,
        SupplementalRegisteredAgent,
        SupplementalDateRA,
        SupplementalClubhouse,
        SupplementalAssessments,
        SupplementalWhatIntervals,
        SupplementalAvailableToRent,
        SupplementalPrice,
        SupplementalTheaterSeatingAmount,
        SupplementalTableChairsAmount,
        SupplementalTypeOfTables,
        SupplementalAdditionalNotes,
    } = req.body;
    // Update MAL entry with object data
    MAL.update(
            {MALrelatedID: malID,
                designatedSiteAddress: SupplementalDesignatedSiteAddress,
                city: SupplementalCity,
                zipCode: SupplementalZipCode,
                phoneNumber: SupplementalPhoneNumber,
                associationWebsite: SupplementalAssociationWebsite,
                associationEmail: SupplementalAssociationEmail,
                numberUnitsLotsDeveloped: SupplementalNumberUnitsLotsDeveloped,
                community55Plus: SupplementalCommunity55Plus,
                associationControlledBy: SupplementalAssociationControlledBy,
                approxTurnoverDate: SupplementalApproxTurnoverDate,
                masterOrSub: SupplementalMasterOrSub,
                subAssociations: SupplementalSubAssociations,
                masterAssociation: SupplementalMasterAssociation,
                registeredAgent: SupplementalRegisteredAgent,
                dateRA: SupplementalDateRA,
                clubhouse: SupplementalClubhouse,
                assessments: SupplementalAssessments,
                whatIntervals: SupplementalWhatIntervals,
                availableToRent: SupplementalAvailableToRent,
                price: SupplementalPrice,
                theaterSeatingAmount: SupplementalTheaterSeatingAmount,
                tableChairsAmount: SupplementalTableChairsAmount,
                typeOfTables: SupplementalTypeOfTables,
                additionalNotes: SupplementalAdditionalNotes},
            {where: {id:req.params.id}}
        )
        .catch(err => {
            console.log(err);
            req.flash('failure','Failed to update MAL entry\'s mal.model.js');
        });
    
    res.redirect("../../mal/entry/" + req.params.id);
});




// Function to convert dates retrieved from views to MySQL date datatype
// This function is currently not in use
// function databaseDate(dateVal) {
//     if (dateVal == null) {
//         return null;
//     }
//     temp = new Date(dateVal);
//     // Return justy YYYY-MM-DD
//     return temp.toISOString().substring(0,10);
// } 

module.exports = router;