/*
    ROUTING MODEL for MML
*/

const express = require('express');
const router = express.Router();
// const passport = require('passport');
const moment = require('moment');
const db = require("../models");

const multer = require('multer');
const upload = multer();
const open = require('open');

// User model
const User = db.users;
const Update = db.updates;
const MML = db.mml;
const ManagementCompany = db.managementCompany;
const GeneralInformation = db.generalInformation;
const BusinessInformation = db.businessInformation;
const OnSiteInformation = db.onSiteInformation;
const StaffInformation = db.staffInformation;
const HomeInformation = db.homeInformation;
const SocialMediaExtras = db.socialMediaExtras;
const Referrals = db.referrals;

// Ensure authenticated user is logged in
const {
    ensureAuthenticated
} = require('../config/auth');

// Ensure user does not have readOnly
const {
    ensureReadOnlyMML
} = require('../config/readOnlyMML');

// ------------------------------------------------------------------

// GET home page
router.get('/dashboard', ensureAuthenticated, async function (req, res, next) {
    req.flash('success', "Please choose a utility from the sidebar");
    res.locals.message = req.flash();
    req.app.locals.user = req.user;
    req.app.locals.listingMML = await MML.findAll(
        { plain: true }
    );
    res.render('pages/mml/dashboard', );
});

// GET create page
router.get('/create', ensureReadOnlyMML, async function (req, res, next) {
    req.app.locals.user = req.user;
    req.app.locals.date = moment().format('MMMM Do YYYY');
    res.render('pages/mml/create', );
});



// Create handle
// TODO: [Transactions] Force atomicity on this entire route.
router.post('/create', ensureReadOnlyMML, function (req, res, next) {
    var mmlID;
    // Create mml object
    var newEntry = {
        // --Metadata--
        // creation: AUTOGENERATED,
        originator: req.user.fName + " " + req.user.lName,
    };
    // Replace all empty string values with NULL
    for (let key of Object.keys(newEntry)){
        if (newEntry[key] == '') {
            newEntry[key] = null;
        }
    }
    // Create MML entry with object data
    MML.create(newEntry)
                .then(data => {
                    // record entry ID
                    mmlID = data.id;

                    // updates.model.js -------------------------------------------------------------------------------------------------
                    // TODO: Uncomment and modify to support MMLs
                    /* const {
                        UpdateNote
                    } = req.body;
                    // update tracking JSON
                    updateTrackingJSON = {
                        "type":"CREATE",
                        "log": [
                            { "field":"", "before":"", "after":"" },
                        ]
                    }
                    // Record attributes
                    var entryUpdate = {
                        MALrelatedID: malID,
                        relatedTable: 'MAL',
                        updateAuthor: data.originator,
                        updateTracking: JSON.stringify(updateTrackingJSON),
                        updateNote: UpdateNote
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryUpdate)){
                        if (entryUpdate[key] == '') {
                            entryUpdate[key] = null;
                        }
                    }
                    // Create new update record
                    Update.create(entryUpdate)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MAL entry\'s *UPDATE* record not added.');
                        }); */

                    

                    // mml_ManagementCompany.model.js -----------------------------------------------------------------------------
                    const {
                        // View element values
                        ManagementMgmtCoID,
                        ManagementMgmtCoAssnSeminarNameTag,
                        ManagementCompanyType,
                    } = req.body;
                    // Record attributes
                    var entryManagement = {
                        MMLrelatedID: mmlID,
                        mgmtCoID: ManagementMgmtCoID,
                        mgmtCoAssnSeminarNameTag: ManagementMgmtCoAssnSeminarNameTag,
                        companyType: ManagementCompanyType
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryManagement)){
                        if (entryManagement[key] == '') {
                            entryManagement[key] = null;
                        }
                    }
                    // Create new ManagementCompany record
                    ManagementCompany.create(entryManagement)
                        .then(data1 => {
                            // Update MML entry with corresponding ManagementCompany table ID
                            MML.update(
                                {managementCompanyID: data1.id},
                                {where: {id:mmlID}}
                            )
                            .catch(err => {
                                console.log(err);
                                req.flash('failure','Failed to update MML entry\'s "managementCompanyID"');
                            });
                        })
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MML entry\'s *mml_ManagementCompany* record not added.');
                        });

                    

                    // mml_GeneralInformation.model.js -----------------------------------------------------------------------------
                    const {
                        // View element values
                        GeneralMktgStatus,
                        GeneralStatusCategory,
                        GeneralLicense,
                        GeneralLicenseNo,
                        GeneralLicenseDate,
                        GeneralTitle,
                        GeneralGender,
                        GeneralFirstName,
                        GeneralLastName,
                        GeneralOtherNames,
                        GeneralPreferredTitle,
                        GeneralDispositionTowardCM,
                    } = req.body;
                    // Record attributes
                    var entryGeneral = {
                        MMLrelatedID: mmlID,
                        mktgStatus: GeneralMktgStatus,
                        statusCategory: GeneralStatusCategory,
                        license: GeneralLicense,
                        licenseNo: GeneralLicenseNo,
                        licenseDate: GeneralLicenseDate,
                        title: GeneralTitle,
                        gender: GeneralGender,
                        firstName: GeneralFirstName,
                        lastName: GeneralLastName,
                        otherNames: GeneralOtherNames,
                        preferredTitle: GeneralPreferredTitle,
                        dispositionTowardCM: GeneralDispositionTowardCM
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryGeneral)){
                        if (entryGeneral[key] == '') {
                            entryGeneral[key] = null;
                        }
                    }
                    // Create new GeneralInformation record
                    GeneralInformation.create(entryGeneral)
                        .then(data1 => {
                            // Update MML entry with corresponding GeneralInformation table ID
                            MML.update(
                                {generalInformationID: data1.id},
                                {where: {id:mmlID}}
                            )
                            .catch(err => {
                                console.log(err);
                                req.flash('failure','Failed to update MML entry\'s "generalInformationID"');
                            });
                        })
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MML entry\'s *mml_GeneralInformation* record not added.');
                        });
                    



                    // mml_BusinessInformation.model.js -----------------------------------------------------------------------------
                    const {
                        // View element values
                        BusinessWorkBranchAddress,
                        BusinessCity,
                        BusinessState,
                        BusinessZip,
                        BusinessCounty,
                        BusinessLandlinePhone,
                        BusinessExtension,
                        BusinessCellPhone,
                        BusinessFax,
                        BusinessTollFree,
                        BusinessWorkEmail,
                        BusinessWorkNotes,
                    } = req.body;
                    // Record attributes
                    var entryBusiness = {
                        MMLrelatedID: mmlID,
                        workBranchAddress: BusinessWorkBranchAddress,
                        city: BusinessCity,
                        state: BusinessState,
                        zip: BusinessZip,
                        county: BusinessCounty,
                        landlinePhone: BusinessLandlinePhone,
                        extension: BusinessExtension,
                        cellPhone: BusinessCellPhone,
                        fax: BusinessFax,
                        tollFree: BusinessTollFree,
                        workEmail: BusinessWorkEmail,
                        workNotes: BusinessWorkNotes
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryBusiness)){
                        if (entryBusiness[key] == '') {
                            entryBusiness[key] = null;
                        }
                    }
                    // Create new BusinessInformation record
                    BusinessInformation.create(entryBusiness)
                        .then(data1 => {
                            // Update MML entry with corresponding BusinessInformation table ID
                            MML.update(
                                {businessInformationID: data1.id},
                                {where: {id:mmlID}}
                            )
                            .catch(err => {
                                console.log(err);
                                req.flash('failure','Failed to update MML entry\'s "businessInformationID"');
                            });
                        })
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MML entry\'s *mml_BusinessInformation* record not added.');
                        });



                    // mml_OnSiteInformation.model.js -----------------------------------------------------------------------------
                    const {
                        // View element values
                        OnSiteAddress,
                        OnSiteCity,
                        OnSiteState,
                        OnSiteZip,
                        OnSiteCounty,
                        OnSiteLandlinePhone,
                        OnSiteExtension,
                        OnSiteCellPhone,
                        OnSiteFax,
                        OnSiteTollFree,
                        OnSiteWorkEmail,
                        OnSiteWorkNotes,
                    } = req.body;
                    // Record attributes
                    var entryOnSite = {
                        MMLrelatedID: mmlID,
                        address: OnSiteAddress,
                        city: OnSiteCity,
                        state: OnSiteState,
                        zip: OnSiteZip,
                        county: OnSiteCounty,
                        landlinePhone: OnSiteLandlinePhone,
                        extension: OnSiteExtension,
                        cellPhone: OnSiteCellPhone,
                        fax: OnSiteFax,
                        tollFree: OnSiteTollFree,
                        workEmail: OnSiteWorkEmail,
                        workNotes: OnSiteWorkNotes
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryOnSite)){
                        if (entryOnSite[key] == '') {
                            entryOnSite[key] = null;
                        }
                    }
                    // Create new OnSiteInformation record
                    OnSiteInformation.create(entryOnSite)
                        .then(data1 => {
                            // Update MML entry with corresponding OnSiteInformation table ID
                            MML.update(
                                {onSiteInformationID: data1.id},
                                {where: {id:mmlID}}
                            )
                            .catch(err => {
                                console.log(err);
                                req.flash('failure','Failed to update MML entry\'s "onSiteInformationID"');
                            });
                        })
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MML entry\'s *mml_OnSiteInformation* record not added.');
                        });



                    // mml_StaffInformation.model.js -----------------------------------------------------------------------------
                    const {
                        // View element values
                        StaffAssistantName,
                        StaffPhone,
                        StaffExtension,
                        StaffOnSiteAddress,
                        StaffCity,
                        StaffState,
                        StaffZip,
                        StaffCounty,
                        StaffLandlinePhone,
                        StaffLandlineExtension,
                        StaffCellPhone,
                        StaffFax,
                        StaffTollFree,
                        StaffOnSiteEmail,
                    } = req.body;
                    // Record attributes
                    var entryStaff = {
                        MMLrelatedID: mmlID,
                        assistantName: StaffAssistantName,
                        phone: StaffPhone,
                        extension: StaffExtension,
                        onSiteAddress: StaffOnSiteAddress,
                        city: StaffCity,
                        state: StaffState,
                        zip: StaffZip,
                        county: StaffCounty,
                        landlinePhone: StaffLandlinePhone,
                        landlineExtension: StaffLandlineExtension,
                        cellPhone: StaffCellPhone,
                        fax: StaffFax,
                        tollFree: StaffTollFree,
                        onSiteEmail: StaffOnSiteEmail,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryStaff)){
                        if (entryStaff[key] == '') {
                            entryStaff[key] = null;
                        }
                    }
                    // Create new StaffInformation record
                    StaffInformation.create(entryStaff)
                        .then(data1 => {
                            // Update MML entry with corresponding StaffInformation table ID
                            MML.update(
                                {staffInformationID: data1.id},
                                {where: {id:mmlID}}
                            )
                            .catch(err => {
                                console.log(err);
                                req.flash('failure','Failed to update MML entry\'s "staffInformationID"');
                            });
                        })
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MML entry\'s *mml_StaffInformation* record not added.');
                        });



                    // mml_HomeInformation.model.js -----------------------------------------------------------------------------
                    // Record attributes
                    const {
                        // View element values
                        HomeMktgStatus,
                        HomeStatusCategory,
                        HomeAddress,
                        HomeCity,
                        HomeState,
                        HomeZip,
                        HomeCounty,
                        HomeEmailAddress,
                        HomeHomePhone,
                        HomeHomeNotes,
                    } = req.body;
                    // Record attributes
                    var entryHome = {
                        MMLrelatedID: mmlID,
                        mktgStatus: HomeMktgStatus,
                        statusCategory: HomeStatusCategory,
                        address: HomeAddress,
                        city: HomeCity,
                        state: HomeState,
                        zip: HomeZip,
                        county: HomeCounty,
                        emailAddress: HomeEmailAddress,
                        homePhone: HomeHomePhone,
                        homeNotes: HomeHomeNotes
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryHome)){
                        if (entryHome[key] == '') {
                            entryHome[key] = null;
                        }
                    }
                    // Create new HomeInformation record
                    HomeInformation.create(entryHome)
                        .then(data1 => {
                            // Update MML entry with corresponding HomeInformation table ID
                            MML.update(
                                {homeInformationID: data1.id},
                                {where: {id:mmlID}}
                            )
                            .catch(err => {
                                console.log(err);
                                req.flash('failure','Failed to update MML entry\'s "homeInformationID"');
                            });
                        })
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MML entry\'s *mml_HomeInformation* record not added.');
                        });



                    // mml_SocialMediaExtras.model.js -----------------------------------------------------------------------------
                    const {
                        // View element values
                        SocialChristmasCard,
                        SocialBirthdayEmail,
                        SocialFacebookAuthorizationDate,
                        SocialNewsletterAuthorization,
                        SocialWillSendPhoto,
                        SocialPhotoFurnished,
                        SocialDeclinedAllBirthday,
                        SocialFollowCMOnFB,
                        SocialFollowUpFB,
                        SocialFollowedDateFB,
                        SocialFollowCMOnLI,
                        SocialFollowUpLI,
                        SocialFollowedDateLI,
                        SocialOfferedFollowAFS,
                        SocialFollowUpAFS,
                        SocialFollowedDateAFS,
                        SocialFacebook,
                        SocialLinkedIn,
                        SocialInstagram,
                        SocialTwitter,
                        SocialNone,
                    } = req.body;
                    // Record attributes
                    var entrySocial = {
                        MMLrelatedID: mmlID,
                        christmasCard: SocialChristmasCard,
                        birthdayEmail: SocialBirthdayEmail,
                        facebookAuthorizationDate: SocialFacebookAuthorizationDate,
                        newsletterAuthorization: SocialNewsletterAuthorization,
                        willSendPhoto: SocialWillSendPhoto,
                        photoFurnished: SocialPhotoFurnished,
                        declinedAllBirthday: SocialDeclinedAllBirthday,
                        followCMOnFB: SocialFollowCMOnFB,
                        followUpFB: SocialFollowUpFB,
                        followedDateFB: SocialFollowedDateFB,
                        followCMOnLI: SocialFollowCMOnLI,
                        followUpLI: SocialFollowUpLI,
                        followedDateLI: SocialFollowedDateLI,
                        offeredFollowAFS: SocialOfferedFollowAFS,
                        followUpAFS: SocialFollowUpAFS,
                        followedDateAFS: SocialFollowedDateAFS,
                        facebook: SocialFacebook,
                        linkedIn: SocialLinkedIn,
                        instagram: SocialInstagram,
                        twitter: SocialTwitter,
                        none: SocialNone,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entrySocial)){
                        if (entrySocial[key] == '') {
                            entrySocial[key] = null;
                        }
                    }
                    // Create new SocialMediaExtras record
                    SocialMediaExtras.create(entrySocial)
                        .then(data1 => {
                            // Update MML entry with corresponding SocialMediaExtras table ID
                            MML.update(
                                {socialMediaExtrasID: data1.id},
                                {where: {id:mmlID}}
                            )
                            .catch(err => {
                                console.log(err);
                                req.flash('failure','Failed to update MML entry\'s "socialMediaExtrasID"');
                            });
                        })
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MML entry\'s *mml_SocialMediaExtras* record not added.');
                        });



                    // --Seminars 2020 ????--
                    // TODO



                    // --Gifts--
                    // TODO



                    // --Law Firm Preferences--
                    // TODO



                    // --Associations Managed--
                    // TODO



                    // -- Referrals--
                    /*
                        - Table: "mml_Referrals.model.js"
                        - One to Many Association — Not able to associate both ways; ID not logged below
                    */
                   // mml_Referrals.model.js -------------------------------------------------------------------------------
                   const {
                        ReferralsReferralDate,
                        ReferralsStaff,
                        ReferralsDateEntered,
                        ReferralsMgmtCoName,
                        ReferralsOffice,
                        ReferralsLegalNameReferredAssociation,
                        ReferralsCounty,
                        ReferralsReferralTitle,
                        ReferralsReferralSource,
                        ReferralsStatus,
                        ReferralsGift,
                        ReferralsReferralPriority,
                        ReferralsReferralType,
                        ReferralsssociationWentTo,
                        ReferralsStaffInitials,
                        ReferralsDateClosed,
                        ReferralsNotes,
                    } = req.body;
                    //
                    var entryReferrals = {
                        MMLrelatedID: mmlID,
                        referralDate: ReferralsReferralDate,
                        staff: ReferralsStaff,
                        dateEntered: ReferralsDateEntered,
                        mgmtCoName: ReferralsMgmtCoName,
                        office: ReferralsOffice,
                        legalNameReferredAssociation: ReferralsLegalNameReferredAssociation,
                        county: ReferralsCounty,
                        referralTitle: ReferralsReferralTitle,
                        referralSource: ReferralsReferralSource,
                        status: ReferralsStatus,
                        gift: ReferralsGift,
                        referralPriority: ReferralsReferralPriority,
                        referralType: ReferralsReferralType,
                        associationWentTo: ReferralsssociationWentTo,
                        staffInitials: ReferralsStaffInitials,
                        dateClosed: ReferralsDateClosed,
                        notes: ReferralsNotes,
                    };
                    // Replace all empty string values with NULL
                    for (let key of Object.keys(entryReferrals)){
                        if (entryReferrals[key] == '') {
                            entryReferrals[key] = null;
                        }
                    }
                    // Create new Referrals record
                    Referrals.create(entryReferrals)
                        .catch(err => {
                            console.log(err);
                            req.flash('failure','New MML entry\'s *mml_Referrals* record not added.');
                        });



                    // Final success code -------------------------------------------------------------------------------------------------
                    req.flash('success','New MML entry successfully added.');
                    res.locals.message = req.flash();
                    // mmlID is a variable that stores the ID of a record's ID
                    // What would be the correct syntax to pass the ID along?
                    res.redirect("../mml/entry/" + mmlID);
                })
                .catch(err => {
                    console.log(err);
                    req.flash('failure','New MML entry not added.');
                    res.locals.message = req.flash();
                    res.redirect("../mml/create");
                });

});






module.exports = router;